#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.6 on Sun Jan 23 10:47:52 2022
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
import matplotlib
from matplotlib.figure import Figure
from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg as FigureCanvas
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((983, 676))
        
        # Menu Bar
        self.frame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.ID_ANY, "&New", "")
        wxglade_tmp_menu.Append(wx.ID_ANY, "&Save", "")
        wxglade_tmp_menu.Append(wx.ID_ANY, "&Export", "")
        wxglade_tmp_menu.Append(wx.ID_ANY, "&Save as", "")
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(wx.ID_ANY, "E&xit", "")
        self.frame_menubar.Append(wxglade_tmp_menu, "&File")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.ID_ANY, "&about fibGet", "")
        self.frame_menubar.Append(wxglade_tmp_menu, "&About")
        self.SetMenuBar(self.frame_menubar)
        # Menu Bar end
        
        # Tool Bar
        self.frame_toolbar = wx.ToolBar(self, -1, style=wx.TB_DEFAULT_STYLE)
        self.SetToolBar(self.frame_toolbar)
        # Tool Bar end
        self.text_ctrl_2 = wx.TextCtrl(self, wx.ID_ANY, "./sample/test.csv")
        self.button_2 = wx.Button(self, wx.ID_ANY, u"…")
        self.panel_2 = wx.Panel(self, wx.ID_ANY)
        self.text_ctrl_gx = wx.TextCtrl(self.panel_2, wx.ID_ANY, "", style=wx.BORDER_NONE | wx.TE_READONLY | wx.TE_RIGHT)
        self.text_ctrl_gy = wx.TextCtrl(self.panel_2, wx.ID_ANY, "", style=wx.BORDER_NONE | wx.TE_READONLY | wx.TE_RIGHT)
        figure = self.matplotlib_figure = Figure(tight_layout=True)
        # 1x1 grid, first subplot
        self.matplotlib_axes = figure.add_subplot(111)
        self.matplotlib_canvas = FigureCanvas(self, wx.ID_ANY, figure)
        figure2 = self.matplotlib_figure2 = Figure(tight_layout=True)
        # 1x1 grid, first subplot
        self.matplotlib_axes2 = figure2.add_subplot(111)
        self.matplotlib_canvas2 = FigureCanvas(self, wx.ID_ANY, figure2)
        self.panel_4 = wx.Panel(self, wx.ID_ANY)
        self.text_ctrl_reqaw = wx.TextCtrl(self.panel_4, wx.ID_ANY, "", style=wx.BORDER_NONE | wx.TE_READONLY | wx.TE_RIGHT)
        figure3 = self.matplotlib_figure3 = Figure(tight_layout=True)
        # 1x1 grid, first subplot
        self.matplotlib_axes3 = figure3.add_subplot(111)
        self.matplotlib_canvas3 = FigureCanvas(self, wx.ID_ANY, figure3)
        self.button_7 = wx.Button(self, wx.ID_ANY, "Run")
        self.button_5 = wx.Button(self, wx.ID_ANY, "Save")
        self.button_4 = wx.Button(self, wx.ID_ANY, "Cancel")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnChooseOutputFile, self.button_2)
        self.Bind(wx.EVT_BUTTON, self.OnExec, self.button_7)
        self.Bind(wx.EVT_BUTTON, self.OnSave, self.button_5)
        self.Bind(wx.EVT_BUTTON, self.OnCancel, self.button_4)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("WallGet")
        self.SetBackgroundColour(wx.Colour(47, 47, 47))
        self.SetForegroundColour(wx.Colour(0, 0, 0))
        self.frame_toolbar.Realize()
        self.text_ctrl_gx.SetBackgroundColour(wx.Colour(47, 47, 47))
        self.text_ctrl_gx.SetForegroundColour(wx.Colour(192, 192, 192))
        self.text_ctrl_gy.SetBackgroundColour(wx.Colour(47, 47, 47))
        self.text_ctrl_gy.SetForegroundColour(wx.Colour(192, 192, 192))
        self.matplotlib_canvas2.SetMinSize((250, 250))
        self.text_ctrl_reqaw.SetBackgroundColour(wx.Colour(47, 47, 47))
        self.text_ctrl_reqaw.SetForegroundColour(wx.Colour(192, 192, 192))
        self.matplotlib_canvas3.SetMinSize((250, 250))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_17 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_20 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_18 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        label_3 = wx.StaticText(self, wx.ID_ANY, "Control file", style=wx.ALIGN_CENTER)
        label_3.SetForegroundColour(wx.Colour(192, 192, 192))
        sizer_4.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)
        sizer_4.Add(self.text_ctrl_2, 2, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)
        sizer_4.Add(self.button_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)
        sizer_1.Add(sizer_4, 0, wx.EXPAND, 0)
        label_5 = wx.StaticText(self.panel_2, wx.ID_ANY, "Gravity Center:")
        label_5.SetMinSize((150, 16))
        label_5.SetForegroundColour(wx.Colour(192, 192, 192))
        sizer_3.Add(label_5, 0, wx.ALL, 1)
        label_12 = wx.StaticText(self.panel_2, wx.ID_ANY, "gx=")
        label_12.SetForegroundColour(wx.Colour(192, 192, 192))
        sizer_5.Add(label_12, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_5.Add(self.text_ctrl_gx, 0, 0, 0)
        label_13 = wx.StaticText(self.panel_2, wx.ID_ANY, "m")
        label_13.SetMinSize((50, 16))
        label_13.SetForegroundColour(wx.Colour(192, 192, 192))
        sizer_5.Add(label_13, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_3.Add(sizer_5, 0, wx.EXPAND, 0)
        label_18 = wx.StaticText(self.panel_2, wx.ID_ANY, "gy=")
        label_18.SetForegroundColour(wx.Colour(192, 192, 192))
        sizer_18.Add(label_18, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_18.Add(self.text_ctrl_gy, 0, 0, 0)
        label_19 = wx.StaticText(self.panel_2, wx.ID_ANY, "m")
        label_19.SetForegroundColour(wx.Colour(192, 192, 192))
        sizer_18.Add(label_19, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_3.Add(sizer_18, 0, wx.EXPAND, 0)
        self.panel_2.SetSizer(sizer_3)
        sizer_10.Add(self.panel_2, 0, wx.EXPAND, 0)
        sizer_10.Add(self.matplotlib_canvas, 1, wx.ALL | wx.EXPAND, 5)
        sizer_7.Add(sizer_10, 5, wx.ALL | wx.EXPAND, 0)
        label_1 = wx.StaticText(self, wx.ID_ANY, "Demand Wall Area")
        label_1.SetMinSize((115, 20))
        label_1.SetForegroundColour(wx.Colour(192, 192, 192))
        sizer_2.Add(label_1, 0, 0, 0)
        sizer_8.Add(self.matplotlib_canvas2, 1, wx.ALL | wx.EXPAND, 0)
        sizer_2.Add(sizer_8, 0, 0, 0)
        label_20 = wx.StaticText(self.panel_4, wx.ID_ANY, "ReqAw=")
        label_20.SetMinSize((100, 16))
        label_20.SetForegroundColour(wx.Colour(192, 192, 192))
        sizer_20.Add(label_20, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_20.Add(self.text_ctrl_reqaw, 0, 0, 0)
        label_21 = wx.StaticText(self.panel_4, wx.ID_ANY, "mm2")
        label_21.SetForegroundColour(wx.Colour(192, 192, 192))
        sizer_20.Add(label_21, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        self.panel_4.SetSizer(sizer_20)
        sizer_2.Add(self.panel_4, 0, wx.EXPAND, 0)
        label_2 = wx.StaticText(self, wx.ID_ANY, "Eccentricity ratio")
        label_2.SetMinSize((107, 20))
        label_2.SetForegroundColour(wx.Colour(192, 192, 192))
        sizer_2.Add(label_2, 0, 0, 0)
        sizer_17.Add(self.matplotlib_canvas3, 1, wx.ALL | wx.EXPAND, 0)
        sizer_2.Add(sizer_17, 0, 0, 0)
        sizer_7.Add(sizer_2, 0, wx.ALL | wx.EXPAND, 0)
        sizer_1.Add(sizer_7, 2, wx.EXPAND, 0)
        sizer_13.Add((350, 20), 5, 0, 0)
        sizer_13.Add(self.button_7, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        sizer_13.Add(self.button_5, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        sizer_13.Add(self.button_4, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 1)
        sizer_1.Add(sizer_13, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def OnChooseOutputFile(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnChooseOutputFile' not implemented!")
        event.Skip()

    def OnExec(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnExec' not implemented!")
        event.Skip()

    def OnSave(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnSave' not implemented!")
        event.Skip()

    def OnCancel(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnCancel' not implemented!")
        event.Skip()

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
